validations:
  purchases:
    required_fields:
      - vendor_id
      - purchase_order_number
      - purchase_date
      - purchase_amount
    field_types:
      vendor_id: 'int'
      purchase_order_number: 'str'
      purchase_date: 'str'
      purchase_amount: 'float'
    field_values:
      purchase_amount:
        min: 0.01
      purchase_status:
        allowed_values: ['Pending', 'Shipped', 'Delivered', 'Cancelled']
    custom_rules:
      check_purchase_date: 'lambda data: data["purchase_date"] <= datetime.now().strftime("%Y-%m-%d")'