# src/configs/config_management/general_config.yaml

paths:
  database: "{{DATABASE_DIR}}/inventory.db"
  schema: "{{DATABASE_DIR}}/schema.sql"
  styles: "{{RESOURCES_DIR}}/styles.qss"
  
logging:
  level: DEBUG
  ring_buffer_capacity: 100